id: V3.3.13
category:
  id: V3
  name: Integrate (CI*)
sub_category:
  id: V3.3
  name: Continuous Security Checks
description: |-
  Verify that Infrastructure as Code (IaC) tools are configured to enforce security policies
level: 1
mappings:
  nist_800_53:
    items:
      - CM-6
  owasp_cicd:
    items:
      - CICD-SEC-7
  cwe:
    items:
      - id: CWE-1104
        description: Use of Unmaintained Third Party Components - Secrets detection tool updates
metadata:
  status: active
