id: V2.2.6
category:
  id: V2
  name: Develop
sub_category:
  id: V2.2
  name: Software Quality
description: |-
  Verify that code quality tools are configured to flag insecure coding patterns
level: 1
mappings:
  nist_800_53:
    items:
      - SA-15
  owasp_cicd:
    items:
      - CICD-SEC-4
  cwe:
    items:
      - id: CWE-398
        description: Indicator of Poor Code Quality
      - id: CWE-1041
        description: Use of Redundant Code - Automated code analysis
metadata:
  status: active
